name: arm
on: [push]

jobs:
  build_arm:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
    runs-on: [self-hosted]
    env: 
      BUILD_TYPE: ${{matrix.build_type}}
    steps:
    - uses: actions/checkout@v2
    - name: install dependency
      run: |
        wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
        python3 install.py -install -tool
    - name: Create Build Environment
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make
    - name: Test
      shell: bash
      run: |
        ./bin/ot 1 12345 20 & ./bin/ot 2 12345 20 
        ./bin/ferret 1 12345 20 & ./bin/ferret 2 12345 20
